Fix remove snaps from subjects
MetaMask/snaps-monorepo pull request #1194
Opened 2023-02-15 20:44 UTC by hmalik88

There was an oversight in the initial implementation of the `removeSnapsFromSubjects`, code was updated to account for a scenario where an origin no longer has any snaps permitted.

2023-02-15 21:54 UTC, Mrtenz requested changes

2023-02-15 21:54 UTC, Mrtenz commented on packages/snaps-controllers/src/snaps/SnapController.ts
> +        }
Please add a test for both of these cases.

2023-02-19 12:06 UTC, FrederikBolding submitted a review, later dismissed

2023-02-20 13:00 UTC, FrederikBolding approved these changes

2023-02-20 13:00 UTC, merged