Add `Math` endowment factory that throws on `Math.random`
MetaMask/snaps-monorepo pull request #888
Opened 2022-10-31 09:40 UTC by Mrtenz

Closes #885.

This adds an endowment factory for `Math`, which replaces the implementation of `Math.random` to throw an error instead.

2022-10-31 09:41 UTC, Mrtenz commented on packages/execution-environments/src/common/endowments/math.ts
> +        );
This could be replaced with a cryptographically secure implementation, i.e.,

```ts
return crypto.getRandomValues(new Uint32Array(1))[0] / 2 ** 32;
```

2022-10-31 09:41 UTC, FrederikBolding commented on packages/execution-environments/src/common/endowments/math.ts
> +        );
If we don't do that, this should be marked as breaking change

2022-10-31 09:42 UTC, Mrtenz commented on packages/execution-environments/src/common/endowments/math.ts
> +        );
@naugtur Any thoughts on this?

2022-10-31 09:43 UTC, FrederikBolding commented on packages/execution-environments/src/common/endowments/index.test.ts
>          'Buffer',
Unrelated, but can we remove `Buffer` from these tests now? I must have forgotten to do so.

2022-10-31 12:24 UTC, naugtur commented on packages/execution-environments/src/common/endowments/math.ts
> +        );
I appreciate the idea, but oppose it with all my power.
We don't want to create an environment in which it's ok to use Math.random

> To increase everyone's safety we've made the only gun in the world that's safe to aim at your own foot. Look for our brand when aiming guns.

2022-10-31 12:39 UTC, FrederikBolding commented on packages/execution-environments/src/common/endowments/math.ts
> +        );
I'm not sure I understand this argument. The idea with replacing `Math.random` is not to make it suitable for generating keys, but making it not be usable as a side-channel. 

Am I missing something?

2022-10-31 14:54 UTC, naugtur commented on packages/execution-environments/src/common/endowments/math.ts
> +        );
@FrederikBolding I'm complaining about it becoming a better version of math.random if it returns cryptographically-safe numbers. Could lead to people using lazy tech because "it's safe in snaps anyway"

2022-11-09 02:35 UTC, rekmarks requested changes
Further discussion required.

2022-11-11 05:13 UTC, rekmarks commented
This should be re-implemented per @Mrtenz's suggestion:
```typescript
return crypto.getRandomValues(new Uint32Array(1))[0] / 2 ** 32;
```

2022-11-11 09:13 UTC, FrederikBolding commented on packages/snaps-execution-environments/src/common/endowments/math.ts
> +        // prevent side chain attacks of `Math.random` by replacing it with an
```suggestion
        // prevent side channel attacks of `Math.random` by replacing it with an
```

2022-11-11 09:27 UTC, FrederikBolding approved these changes

2022-11-11 09:32 UTC, merged